### ISSUE TITLE
Android 5.0 Lollipop support

### ISSUE THREAD

**Issue by dlewis23** [mano-mykingdom/downloader#2]
When I use your module on Android 5.0 I get the following error when starting a download. I'm testing on a Moto G with TI SDK 3.4.1 GA

[INFO] :   ALERT: (KrollRuntimeThread) [13226,18780] java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference : While downloading file at (index 0 based) = 0

**Comment by eggin** [comment]
I'm having the same issue. Which is a shame 'cause I love how simply this module works. Would love it if you get a chance to look into it. :-)

**Comment by mano-mykingdom** [comment]
6c2f3d5b931f183d4002a8f3727059ae703745af
