### ISSUE TITLE
stopDownload doesn't do anything, and download isn't async

### ISSUE THREAD

**Issue by skoften** [mano-mykingdom/downloader#3]
Working with SDK 4.X.X.

The stopDownload function doesn't seem to respond, untill the download is completed. Also, all of the other UI actions seem to be blocked during the download transfers.

[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   [articleView.js] - cancelDownload() fired
[INFO] :   Download completed successfully

edit: I think I found the cause; when I call the stopDownload() function from a function binded to a view or label, it's ignored. Apparently, it has to be a button. Then it stops. Can this be fixed?

**Comment by mano-mykingdom** [comment]
Can you please share the test case for me to check?

**Comment by manojdcoder** [comment]
c0b98a05dc62ddda4e94feddf1d46aa06c931e8d tested `stopDowload` method with `4.0.0.GA`, works as expected. If you still face any issue, please share the detailed test case.
